title: Participation Wakener
description: Drive social engagement through the visualisation and organisation of information to support decision making
to achieve social govern goals. Themes on digital communication, information design and user-centred design.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
---
layout: default
comments: true
# other options
---
