title: [Participation Wakening]
description: [Drive Social Engagement through The Visualisation and Organisation of Information to Support Decision Making
to Achieve Social and Governance Goals]
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
zip_url: http://example.com/download.zip
another_url: another value
---
layout: default
comments: true
# other options
---
