title: [Participation Wakener]
description: [Drive social engagement through The Visualisation and organisation of information to support decision making
to achieve social and governance goals]
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
zip_url: http://example.com/download.zip
another_url: another value
---
layout: default
comments: true
# other options
---
